drop table if exists VIDEOJUEGOS;
drop table if exists JUGADORES;
drop table if exists USER_ROLES;
drop table if exists USUARIOS;

create table VIDEOJUEGOS(
                        id bigint generated by default as identity PRIMARY KEY,
                        nombre varchar(50) not null,
                        genero varchar(50) not null,
                        fecha_de_creacion date not null,
                        almacenamiento varchar(8) not null,
                        costo decimal(10,2) not null,
                        jugador_id bigint,
                        is_deleted boolean default false,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                        uuid uuid not null unique
);

create table JUGADORES(
                        id bigint generated by default as identity PRIMARY KEY,
                        nombre varchar(50) not null unique,
                        is_deleted boolean default false,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

create table USER_ROLES(
                         user_id bigint not null,
                         roles enum('ADMIN','USER')
);


create table USUARIOS(
                       id bigint generated by default as identity PRIMARY KEY,
                       nombre varchar(255) not null,
                       apellidos varchar(255) not null,
                       username varchar(255) not null unique,
                       email varchar(255) not null unique,
                       password varchar(255) not null,
                       is_deleted boolean default false,
                       created_at timestamp default CURRENT_TIMESTAMP not null,
                       jugador_id bigint unique,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);



alter table if exists videojuegos
  add constraint FK_VIDEOJUEGOS_JUGADORES_JUGADOR_ID
  foreign key (jugador_id)
  references jugadores(id);

alter table if exists user_roles
  add constraint fk_user_roles_usuarios_user_id
  foreign key (user_id)
  references usuarios(id);

alter table if exists usuarios
  add constraint fk_usuarios_jugadores_jugador_id
  foreign key (jugador_id)
  references jugadores(id);
  
INSERT INTO JUGADORES (nombre)
VALUES ('Francock'), ('Juanjsts');

INSERT INTO VIDEOJUEGOS (nombre, genero, almacenamiento, fecha_de_creacion, costo, jugador_id, uuid)
VALUES ('Pepsiman', 'Estrategia', '10 TB', '1994-12-23', 100.0, 1, UUID()),
       ('Adan y Eva', 'Battle Royale', '9 MB', '2024-12-24', 200.0, 2, UUID()),
       ('The Witcher 3: Wild Hunt', 'RPG', '100 GB', '2024-12-24', 300.0, 2, UUID()),
       ('The Last of Us Part II', 'RPG', '100 GB', '2024-12-24', 400.0, 1, UUID()),
       ('The Witcher 3: Wild Hunt', 'RPG', '100 GB', '2024-12-24', 300.0, 2, UUID()),
       ('Las flipantes aventuras de Manuel', 'RPG', '100 GB', '2024-12-24', 400.0, 1, UUID()),
       ('Super Mario Odyssey', 'Plataformas', '6 GB', '2017-10-27', 59.90, 1, UUID()),
       ('Elden Ring', 'RPG', '60 GB', '2022-02-25', 69.90, 2, UUID()),
       ('Hollow Knight', 'Metroidvania', '9 GB', '2017-02-24', 14.99, 1, UUID());


--No está asociado a ningun jugador

-- Contraseña: Admin1
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Admin', 'Admin Fernandez', 'admin','admin@prueba.es','$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2');

insert into USER_ROLES (user_id, roles)
values (1, 'ADMIN');

-- Contraseña: Test1
insert into USUARIOS (nombre, apellidos, username, email, password, jugador_id)
values ('JJSTS', 'Team Yuca', 'jjsts', 'yuquita@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu', 2);
insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Otro1
insert into USUARIOS (nombre, apellidos, username, email, password, jugador_id)
values ('Francock', 'Team Yuca', 'francock', 'franco@prueba.net',
        '$2a$12$3Q4.UZbvBMBEvIwwjGEjae/zrIr6S50NusUlBcCNmBd2382eyU0bS', 1);
insert into USER_ROLES (user_id, roles)
values (1, 'USER');
