/*
-- Borra la tabla si existe
drop table if exists TARJETAS;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular_id varchar(50) not null,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table TITULARES (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null unique,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
);

create table user_roles (
    user_id bigint not null,
    roles enum ('ADMIN','USER')
);

create table usuarios (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    apellidos varchar(255) not null,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    is_deleted boolean default false,
    titular_id bigint not null unique,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
    )

*/
INSERT INTO JUGADORES (nombre)
VALUES ('Francock'), ('Juanjsts');

INSERT INTO VIDEOJUEGOS (nombre, genero, almacenamiento, fecha_de_creacion, costo, jugador_id, uuid)
VALUES 
    -- Juegos Clásicos y Populares
    ('Minecraft', 'Sandbox', '1 GB', '2011-11-18', 26.95, 1, UUID()),
    ('League of Legends', 'MOBA', '22 GB', '2009-10-27', 0.0, 1, UUID()),
    ('Brawl Stars', 'Battle Royale', '350 MB', '2018-12-12', 0.0, 2, UUID()),
    ('Plants vs Zombies', 'Tower Defense', '150 MB', '2009-05-05', 4.99, 2, UUID()),
    ('Fortnite', 'Battle Royale', '80 GB', '2017-07-25', 0.0, 1, UUID()),
    ('Among Us', 'Social Deduction', '250 MB', '2018-06-15', 3.99, 2, UUID()),
    ('Clash of Clans', 'Estrategia', '350 MB', '2012-08-02', 0.0, 1, UUID()),
    ('Clash Royale', 'Estrategia', '400 MB', '2016-03-02', 0.0, 2, UUID()),
    ('PUBG Mobile', 'Battle Royale', '2.5 GB', '2018-03-19', 0.0, 1, UUID()),
    ('Free Fire', 'Battle Royale', '1.2 GB', '2017-12-04', 0.0, 2, UUID());

--No está asociado a ningun jugador

-- Contraseña: Admin1
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Admin', 'Admin Fernandez', 'admin','admin@prueba.es','$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2');

insert into USER_ROLES (user_id, roles)
values (1, 'ADMIN');

-- Contraseña: Test1
insert into USUARIOS (nombre, apellidos, username, email, password, jugador_id)
values ('JJSTS', 'Team Yuca', 'jjsts', 'yuquita@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu', 2);
insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Otro1
insert into USUARIOS (nombre, apellidos, username, email, password, jugador_id)
values ('Francock', 'Team Yuca', 'francock', 'franco@prueba.net',
        '$2a$12$3Q4.UZbvBMBEvIwwjGEjae/zrIr6S50NusUlBcCNmBd2382eyU0bS', 1);
insert into USER_ROLES (user_id, roles)
values (1, 'USER');
