/*
-- Borra la tabla si existe
drop table if exists TARJETAS;
-- Crea la tabla TARJETAS
create table TARJETAS (
    id bigint generated by default as identity PRIMARY KEY,
    numero varchar(19) not null,
    cvc varchar(3) not null,
    fecha_caducidad date not null,
    titular_id varchar(50) not null,
    saldo float(53) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table TITULARES (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null unique,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
);

create table user_roles (
    user_id bigint not null,
    roles enum ('ADMIN','USER')
);

create table usuarios (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    apellidos varchar(255) not null,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    is_deleted boolean default false,
    titular_id bigint not null unique,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
    )

*/
INSERT INTO PLATAFORMAS (nombre, fabricante, tipo, fecha_de_lanzamiento)
VALUES ('Epic Games', 'Epic Games', 'Online', '2024-12-24'),
       ('Steam', 'Valve', 'Online', '2024-12-24');

INSERT INTO VIDEOJUEGOS (nombre, genero, almacenamiento, fecha_de_creacion, costo, plataforma_id, uuid)
VALUES ('Pepsiman', 'Estrategia', '10 TB', '1994-12-23', 100.0, 1, UUID()),
       ('Adan y Eva', 'Battle Royale', '9 MB', '2024-12-24', 200.0, 2, UUID()),
       ('The Witcher 3: Wild Hunt', 'RPG', '100 GB', '2024-12-24', 300.0, 2, UUID()),
       ('The Last of Us Part II', 'RPG', '100 GB', '2024-12-24', 400.0, 1, UUID());


--No está asociado a ninguna plataforma

insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Admin', 'Admin Fernandez', 'admin','admin@prueba.es','$2a$12$RUq2ScW1Kiizu5K4gKoK4OTz80.DWaruhdyfi2lZCB.KeuXTBh0S.');

insert into USER_ROLES (user_id, roles)
values (1, 'USER');

insert into USER_ROLES (user_id, roles)
values (1, 'ADMIN');

-- Contraseña admin: luisitocomunica
insert into USUARIOS (nombre, apellidos, username, email, password, plataforma_id)
values ('Martin', 'Martinez Fernandez', 'martin','martin@prueba.es','luisitocomunica',1);

insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Test1
insert into USUARIOS (nombre, apellidos, username, email, password, plataforma_id)
values ('Steam', 'Steam Test', 'steam', 'steam@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu', 2);
insert into USER_ROLES (user_id, roles)
values (3, 'USER');

-- Contraseña: Otro1
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('María', 'María Otro', 'maría', 'otro@prueba.net',
        '$2a$12$3Q4.UZbvBMBEvIwwjGEjae/zrIr6S50NusUlBcCNmBd2382eyU0bS');
insert into USER_ROLES (user_id, roles)
values (4, 'USER');