
GET http://localhost:3000/api/v1/plataformas

###

GET http://localhost:3000/api/v1/plataformas/1
###

GET http://localhost:3000/api/v1/plataformas/3

### Nueva plataforma
POST http://localhost:3000/api/v1/plataformas
Content-Type: application/json

{
  "nombre" : "Riot Client",
  "fabricante" :"Riot Games",
  "tipo": "PC",
  "fechaDeLanzamiento": "2019-12-31",
  "isDeleted": false
}