
GET http://localhost:3000/api/v1/jugadores

###

GET http://localhost:3000/api/v1/jugadores/1
###

GET http://localhost:3000/api/v1/jugadores/3

### Nuevo jugador
POST http://localhost:3000/api/v1/jugadores
Content-Type: application/json

{
  "nombre" : "TY | JJSTS",
  "isDeleted": false
}
