
GET http://localhost:3000/api/v1/plataformas

###

GET http://localhost:3000/api/v1/plataformas/1
###

GET http://localhost:3000/api/v1/plataformas/3

### Nuevo jugador
POST http://localhost:3000/api/v1/plataformas
Content-Type: application/json

{
  "nombre" : "TY | JJSTS",
  "isDeleted": false
}
