drop table if exists VIDEOJUEGOS;
drop table if exists PLATAFORMAS;

create table VIDEOJUEGOS(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(50) not null,
    genero varchar(50) not null,
    almacenamiento varchar(8) not null,
    fecha_de_creacion date not null,
    costo decimal(10,2) not null,
    plataforma_id bigint,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table PLATAFORMAS(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(50) not null unique,
    fabricante varchar(50) not null,
    tipo varchar(20) not null,
    fecha_de_lanzamiento date not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

alter table if exists videojuegos
     add constraint FK_VIDEOJUEGOS_PLATAFORMAS_PLATAFORMA_ID foreign key (plataforma_id) references plataformas(id);