drop table if exists VIDEOJUEGOS;
drop table if exists PLATAFORMAS;
drop table if exists USER_ROLES;
drop table if exists USUARIOS;

create table VIDEOJUEGOS(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(50) not null,
    genero varchar(50) not null,
    fecha_de_creacion date not null,
    almacenamiento varchar(8) not null,
    costo decimal(10,2) not null,
    plataforma_id bigint,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table PLATAFORMAS(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(50) not null unique,
    fabricante varchar(50) not null,
    tipo varchar(20) not null,
    fecha_de_lanzamiento date not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

create table USER_ROLES(
    user_id bigint not null,
    roles enum('ADMIN','USER')
);


create table USUARIOS(
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    apellidos varchar(255) not null,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    is_deleted boolean default false,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    plataforma_id bigint unique,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);



alter table if exists videojuegos
    add constraint FK_VIDEOJUEGOS_PLATAFORMAS_PLATAFORMA_ID
    foreign key (plataforma_id)
    references plataformas(id);

alter table if exists user_roles
    add constraint fk_user_roles_usuarios_user_id
    foreign key (user_id)
    references usuarios(id);

alter table if exists usuarios
    add constraint fk_usuarios_plataformas_plataforma_id
    foreign key (plataforma_id)
    references plataformas(id):